stages:
  - build
  - test
  - deploy

job 1:
  before_script:
    - wget https://storage.googleapis.com/kubernetes-release/release/v1.11.0/bin/linux/amd64/kubectl /usr/local/bin/kubectl
    - wget https://github.com/kubernetes/kops/releases/download/1.9.1/kops-linux-amd64 /usr/local/bin/kops
  stage: build
  script: echo "success"

