stages:
  - build
  - test
  - deploy

job 1:
  stage: build
  script: echo " job one success"


gcp 1:4:
  stage: test
  script: echo "job gcp success"


aws 2:2:
  stage: test
  script: echo "job aws success"

gcp 2:4:
  stage: test
  script: echo "job aws success"

aws 1:2:
  stage: test
  script: echo "job aws success"

gcp 3:4:
  stage: test
  script: echo "job aws success"
 

job 2:
  stage: deploy
  script: echo " job four success"
