stages:
  - build
  - test
  - deploy

job 1:
  stage: build
  script: echo " job one success"


gcp:
  stage: test
  script: echo "job gcp success"

aws:
  stage: test
  script: echo "job aws success"

gcp vpc:
  stage: test
  script: echo "job aws success"
aws vpc:
  stage: test
  script: echo "job aws success"
gcp cluster:
  stage: test
  script: echo "job aws success"
 

job 2:
  stage: deploy
  script: echo " job four success"
