stages:
  - build
  - test
  - deploy

job 1:
  stage: build
  script: echo " job one success"

job 2:
  stage: build
  script: echo"job two success"

job 3:
  stage: test
  script: echo "job three success"

job 4:
  stage: deploy
  script: echo"job four success"
