stages:
  - build
  - test
  - deploy


job 1:
  stage: build
  script: 
    - set + x 
    - echo " job one success" > test.txt 
  artifacts:
    paths:
      - /binary

gcp 1:3:
  image: atulabhi/kops:v1
  stage: test
  script: 
    - echo "job gcp success"
    - kops version
    - ansible --version
  dependencies:
    - job 1

gcp 2:3:
  stage: test
  script: echo "job aws success"
  dependencies:
    - job 1

gcp 3:3:
  stage: test
  script: echo "job aws success"
  dependencies:
    - job 1 

job 2:
  stage: deploy
  script: echo " job four success"

.job_template: &job_definition  # Hidden key that defines an anchor named 'job_definition'
  image: ruby:2.1

test1:
  <<: *job_definition           # Merge the contents of the 'job_definition' alias
  script:
    - echo "test1 project"

test2:
  <<: *job_definition           # Merge the contents of the 'job_definition' alias
  script:
    - echo "test2 project"
