stages:
  - setup
  - test
  - app-test
  - cleanup
gcp-cluster:
  image: atulabhi/kops:v8
  stage: setup
  script: 
    - ./gcp
  artifacts:
    paths:
      - .kube/

openebs_gcp_deploy:
  image: atulabhi/kops:v8
  stage: test
  dependencies:
    - gcp-cluster
  script:
    - echo "Deploying-Openebs"
    - ls -a
    - pwd
    - mkdir ~/.kube
    - cp  .kube/config ~/.kube/config
    - kubectl config get-contexts
    - wget https://raw.githubusercontent.com/ashishranjan738/testlit/master/setup_openebs.yaml
    - kubectl apply -f setup_openebs.yaml
  artifacts:
    paths:
      - .kube/

apps-gcp-deploy:
  stage: app-test
  script:
   - echo "app-deploy"
  
  dependencies:
    - openebs_gcp_deploy
     
cleanup-gcp:
  image: atulabhi/kops:v8
  dependencies:
    - gcp-cluster
  stage: cleanup
  script: 
   - echo $SDK_TOKEN > key.json
   - gcloud auth activate-service-account --key-file=key.json
   - gcloud config set project openebs-ci
   - export GOOGLE_APPLICATION_CREDENTIALS="/itsmesingh.avneet/e2e-infrastructure/key.json"
   - echo "cleanup"
   - pwd 
   - ls -a
   - ls .kube
   - cat .kube/clusters
   - mkdir ~/logs
   - cp .kube/clusters ~/logs
   - git clone https://github.com/harshvkarn/litmus.git 
   - cd litmus/
   - git checkout gcp-k8s
   - cd k8s/gcp/k8s-installer/
   - echo "cleanup"
   - ansible-playbook delete-k8s-cluster.yml
   - ansible-playbook delete-vpc.yml --extra-vars "vpc_name=openebs-e2e-test"

aws-cluster:
  image: atulabhi/kops:v8
  stage: setup
  script: 
   - echo "creating AWS-vpc"
   - mkdir ~/.aws
   - echo $CONFIG > ~/.aws/config
   - echo $CREDENTIALS > ~/.aws/credentials
   - mkdir aws 
   - mkdir aws/cluster
   - mkdir cluster && cd cluster
   - export AWS_ACCESS_KEY_ID=$AC_ID
   - export AWS_SECRET_ACCESS_KEY=$AC_KEY
   - export AWS_DEFAULT_REGION=eu-west-2
   - export AWS_DEFAULT_OUTPUT=json
   - which ssh-keygen
   - git clone https://github.com/chandankumar4/test.git
   - cd test/k8s/aws/k8s-installer
   - echo "creating vpc"
   - pip list
   - ansible-playbook pre-requisite.yml -vvv
   - echo "creating  cluster"
   - ansible-playbook create-aws-cluster.yml --extra-vars "k8s_version=1.10.0" -vvv
   - wget https://raw.githubusercontent.com/openebs/litmus/master/hack/rbac.yaml
   - kubectl apply -f rbac.yaml
   - cat /tmp/aws/cluster_name.csv >/itsmesingh.avneet/e2e-infrastructure/aws/cluster/cluster_name.csv
   - cat /tmp/aws/id.csv > /itsmesingh.avneet/e2e-infrastructure/aws/cluster/id.csv
   - mkdir /itsmesingh.avneet/e2e-infrastructure/.kube
   - cat ~/.kube/config > /itsmesingh.avneet/e2e-infrastructure/.kube/config
   - kubectl create configmap kubeconfig --from-file=/itsmesingh.avneet/e2e-infrastructure/.kube/config -n litmus
   - cd /itsmesingh.avneet/e2e-infrastructure
   - mv .kube/config aws/

  artifacts:
    paths:
      - aws/

openebs_aws_deploy:
  image: atulabhi/kops:v8
  stage: test
  dependencies:
    - aws-cluster
  script: 
   - echo "deploying OpenEBS on AWS"
   - ls -a
   - ls -a aws
   - pwd
   - mkdir ~/.kube
   - cp  aws/config ~/.kube/config
   - wget https://raw.githubusercontent.com/ashishranjan738/testlit/master/setup_openebs.yaml
   - kubectl apply -f setup_openebs.yaml

apps-aws-deploy:
  image: atulabhi/kops:v8
  stage: app-test
  script: 
   - echo "jobs-aws-started"

cleanup-aws:
  image: atulabhi/kops:v8
  dependencies:
    - aws-cluster
  stage: cleanup
  script: 
   - echo "AWS-Cleanup"
   - pwd
   - ls aws/
   - export AWS_ACCESS_KEY_ID=$AC_ID
   - export AWS_SECRET_ACCESS_KEY=$AC_KEY
   - export AWS_DEFAULT_REGION=eu-west-2
   - export AWS_DEFAULT_OUTPUT=json
   - mkdir /tmp/aws
   - cat aws/cluster/id.csv > /tmp/aws/id.csv
   - cat aws/cluster/cluster_name.csv >/tmp/aws/cluster_name.csv
   - mkdir cluster && cd cluster
   - git clone https://github.com/chandankumar4/test.git
   - cd test/k8s/aws/k8s-installer
   - ansible-playbook delete-aws-cluster.yml
   - ansible-playbook delete-pre-requisite.yml
