stages:
  - build
  - test
  - deploy

job 1:
  stage: build
  script: 
    - set + x 
    - echo " job one success" > test.txt 
  artifacts:
    paths:
      - binaries/

gcp 1:3:
  stage: test
  script: echo "job gcp success"
  dependencies:
    - job 1

aws 2:2:
  stage: test
  script: echo "job aws success"

gcp 2:3:
  stage: test
  script: echo "job aws success"
  dependencies:
    - job 1
aws 1:2:
  stage: test
  script: echo "job aws success"

gcp 3:3:
  stage: test
  script: echo "job aws success"
  dependencies:
    - job 1 

job 2:
  stage: deploy
  script: echo " job four success"
